### ISSUE TITLE
Save could not be completed - some characters cannot be mapped

### ISSUE THREAD

**Issue by KlaasBonnema** [thomas-fritsch/psdt#12]
While postscript does not recommend using characters outside the visible printable subset of the ASCII characterset it is not prohibited. Existing postscript files are using these characters.
PSDT will currently does not allow these files to be saved using CP1252, US-ASCII, ISO-8859-1 encoding.
Is there aan alternative encoding that will allow this?

**Comment by thomas-fritsch** [comment]
I am not sure how to reproduce this problem. I tried various non-ASCII characters and various text-encodings for the ps file,  but never got an error-message on save.

What exactly did you do? And what is your workspace encoding (in Preferences -> General -> Workspace)?

Anyway:  
I think the content-type in [plugin.xml](https://github.com/thomas-fritsch/psdt/blob/master/de.tfritsch.psdt/plugin.xml) should be refined by adding `default-charset="ISO-8859-1"` instead of inheriting the workspace encoding.

**Comment by thomas-fritsch** [comment]
Ok, finally I could reproduce the issue and understand what's going on.  
![save-rror](https://cloud.githubusercontent.com/assets/15331649/22126088/8170a8f8-de96-11e6-8cb8-dc55c1657e21.png)  
The PostScript editor behaves like all eclipse text editors.  

Saving behavior:
* ISO-8859-1: Can save chars `'\u0000'` .. `'\u00FF'`, complains on `'\u0100'` and beyond.
* US-ASCII: Can save chars `'\u0000'` .. `'\u007F'`, complains on `'\u0080'` and beyond.
* UTF-8: Can save everything, never complains.

Reading behavior:
* ISO-8859-1: Bytes `0x00` .. `0xFF` are converted to chars `'\u0000'` .. `'\u00FF'`   (the trivial conversion).
* US-ASCII: Bytes `0x00` .. `0x7F` are converted to chars `'\u0000'` .. `'\u007F'`,  
  bytes `0x80` .. `0xFF` are all converted to char `'\uFFFD'` (the [Unicode Replacement Char](http://www.fileformat.info/info/unicode/char/0fffd/index.htm)).
* CP1252: Bytes `0x00` .. `0x7F` are converted to chars `'\u0000'` .. `'\u007F'`,  
  most bytes `0x80` .. `0xFF` are converted to printable chars,  
  but bytes `0x81`, `0x8D`, `0x8F`, `0x90`, `0x9D` are converted to char `'\uFFFD'`.
* UTF-8: invalid byte-sequences are converted to `'\uFFFD'`

Even though not recommended, PostScript files may contain arbitrary bytes.  
Hence, reading PostScript with encodings US-ASCII, CP1252, UTF-8 is a bad idea, because you are in risk of loosing information (several different bytes end up as the same char `'\uFFFD'`). And on save you may get complaints on the `'\uFFFD'` char.  
Reading PostScript with ISO-8859-1 is the best choice because there never is loss of information. And on save you will get the original byte-content again.
